# Build Settings
build:
  functions: functions
  publish: build
  lifecycle:
    onInit:
      - echo "Starting the build"
    onBuild:
      - npm run makeSite
    onEnd:
      - echo "Ending the build"

# Build plugins
plugins:
  - package: ./plugins/example
    config:
      hi: foo
